use MyLibrary

insert Series values 
(N'Верлорды',N'Wereworld',9,7,null,null,N'https://fantlab.ru/work434429'),
(N'Хроника Убийцы Короля', N'The Kingkiller Chronicle', 1,3,null,null,N'https://fantlab.ru/work188169'),
(N'Сага о Видящих',N' The Farseer Trilogy',2,1,1,1,N'https://fantlab.ru/work3607'),
(N'Сага о живых кораблях',N' The Liveship Traders',2,5,1,2,N'https://fantlab.ru/work3611'),
(N'Сага о Шуте и Убийце',N'The Tawny Man Trilogy',2,1,1,3,N'https://fantlab.ru/work3615'),
(N'Хроники Дождевых чащоб',N'The Rain Wild Chronicles',2,5,1,4,N'https://fantlab.ru/work141631'),
(N'Фитц и шут',N'The Fitz and The Fool Trilogy',2,1,1,5,N'https://fantlab.ru/work528719'),
(N'Кодекс Алеры',N'Codex Alera',7,1,null,null,N'https://fantlab.ru/work40684'),
(N'Море Осколков',N'Shattered Sea',8,1,null,null,N'https://fantlab.ru/work466699'),
(N'Война с демонами',N'The Demon Cycle',13,7,null,null,N'https://fantlab.ru/work178279'),
(N'Трилогия Бартимеуса',N' Bartimaeus Trilogy',14,1,3,1,N'https://fantlab.ru/work23963'),
(N'Гарри Поттер',N'Harry Potter',3,1,2,1,N'https://fantlab.ru/work3650'),
(N'Сказки барда Бидля',N'The Tales of Beedle the Bard',3,6,2,2,N'https://fantlab.ru/work69438'),
(N'История магии в Северной Америке',N'History of Magic in North America',3,6,2,3,N'https://fantlab.ru/work773898'),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),
--(N'',N'',,,,,N''),